import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portifólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const combinedClassName = `${inter.className} bg-slate-200`;

  return (
    <html lang="en">
      <body className={combinedClassName}>
        {children}
      </body>
    </html>
  );
}
